ktor:
  application:
    modules:
      - xyz.hyli.timeflow.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "jwt-secret"
  issuer: "jwt-issuer"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password
email:
  host: "smtp.example.com"
  port: "465"
  username: "your-email@example.com"
  password: "your-password"
  from: "noreply@example.com"
  ssl: true
  codeExpirationMinutes: 10